name: Sync Releases

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间 0 点自动运行
  workflow_dispatch:    # 支持手动触发

jobs:
  sync-releases:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: 安装依赖
      run: sudo apt-get install -y jq

    - name: 获取对方最新 Release
      env:
        UPSTREAM_REPO: portapps/android-studio-portable
      run: |
        response=$(curl -s "https://api.github.com/repos/$UPSTREAM_REPO/releases/latest")
        echo "$response" > upstream_release.json
        echo "TAG_NAME=$(jq -r '.tag_name' upstream_release.json)" >> $GITHUB_ENV
        echo "BODY=$(jq -r '.body' upstream_release.json)" >> $GITHUB_ENV
        jq -r '.assets[].browser_download_url' upstream_release.json > assets.txt

    - name: 检查是否已存在
      run: |
        if curl -s -I "https://github.com/klcb2010/android-studio-portable/releases/tag/$TAG_NAME" | grep -q 'HTTP/2 200'; then
          echo "RELEASE_EXISTS=true" >> $GITHUB_ENV
        else
          echo "RELEASE_EXISTS=false" >> $GITHUB_ENV
        fi

    - name: 创建 Release 并上传文件
      if: env.RELEASE_EXISTS == 'false'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # 创建 Release
        response=$(curl -s -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Content-Type: application/json" \
          -d "{\"tag_name\":\"$TAG_NAME\",\"name\":\"$TAG_NAME\",\"body\":\"$BODY\"}" \
          "https://api.github.com/repos/klcb2010/android-studio-portable/releases")
        
        upload_url=$(echo $response | jq -r '.upload_url' | cut -d'{' -f1)

        # 上传 Assets
        while read asset_url; do
          if [ -n "$asset_url" ]; then
            filename=$(basename "$asset_url")
            curl -s -L -o $filename "$asset_url"
            curl -s -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Content-Type: application/octet-stream" \
              --data-binary @$filename \
              "$upload_url?name=$filename"
          fi
        done < assets.txt
