name: Sync Releases from Upstream 
 
# 触发条件，可以设置定时执行或者手动触发 
on: 
  # 手动触发 
  workflow_dispatch: 
  # 定时触发，例如每天凌晨 2 点 
  schedule: 
    - cron: '0 2 * * *' 
 
jobs: 
  sync-releases: 
    runs-on: ubuntu-latest 
 
    steps: 
      # 步骤 1: 检出自己的仓库代码 
      - name: Checkout my repository 
        uses: actions/checkout@v3 
        with: 
          repository: klcb2010/android-studio-portable 
          token: ${{ secrets.GITHUB_TOKEN }} 
          ref: master 
 
      # 步骤 2: 添加对方仓库为远程仓库 
      - name: Add upstream repository 
        run: | 
          git remote add upstream https://github.com/portapps/android-studio-portable.git  
          git fetch upstream 
 
      # 步骤 3: 拉取对方仓库的最新标签 
      - name: Fetch latest tags from upstream 
        run: git fetch upstream --tags 
 
      # 步骤 4: 合并对方仓库的 master 分支到本地 master 分支 
      - name: Merge upstream master into local master 
        run: | 
          git merge upstream/master --allow-unrelated-histories -m "Merge latest changes from upstream" 
 
      # 步骤 5: 推送更新到自己的仓库 
      - name: Push changes to my repository 
        run: git push origin master 
