name: Sync Releases

on:
  schedule:
    - cron: '0 2 * * *'  # 每天凌晨 2 点执行
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest release from upstream
        id: get_release
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/portapps/android-studio-portable/releases/latest | jq -r '.tag_name')
          echo "LATEST_RELEASE=${LATEST_RELEASE}" >> $GITHUB_ENV

      - name: Check if release exists
        run: |
          if curl -s https://api.github.com/repos/klcb2010/android-studio-portable/releases | jq -r '.[].tag_name' | grep -q "${{ env.LATEST_RELEASE }}"; then
            echo "Release already exists. Skipping."
            exit 0
          fi

      - name: Download assets
        run: |
          RELEASE_ID=$(curl -s https://api.github.com/repos/portapps/android-studio-portable/releases/latest | jq -r '.id')
          ASSETS=$(curl -s https://api.github.com/repos/portapps/android-studio-portable/releases/${RELEASE_ID} | jq -r '.assets[].browser_download_url')
          mkdir -p assets
          for url in $ASSETS; do
            wget -P assets "$url"
          done

      - name: Create a new release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.LATEST_RELEASE }}
          name: ${{ env.LATEST_RELEASE }}
          body: "Synchronized from upstream."
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "assets/*"
