name: Sync upstream master

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 3 * * *'  # 每天 UTC 时间 3:00 (北京时间 11:00)

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 必须的写入权限

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整提交历史
        ref: master     # 明确指定分支

    - name: Configure git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions-bot@users.noreply.github.com"

    - name: Add upstream remote
      run: git remote add upstream https://github.com/portapps/android-studio-portable.git

    - name: Fetch upstream master
      run: |
        git fetch upstream master --tags  # 明确抓取 master 分支

    - name: Merge changes
      run: |
        git checkout master
        git merge --no-commit --no-ff upstream/master  # 安全合并策略
        git commit -m "chore: sync upstream [skip ci]" || echo "No changes to commit"

    - name: Push changes
      run: |
        git push origin master
        git push --tags origin

    - name: Handle failure
      if: ${{ failure() }}
      run: |
        echo "同步失败！请检查冲突或网络问题"
        exit 1
