name: Sync upstream releases

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '0 3 * * *'  # 每天 UTC 时间 3:00 (北京时间 11:00) 自动运行

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 需要写入权限来推送变更

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整历史记录

    - name: Configure git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Add upstream remote
      run: git remote add upstream https://github.com/portapps/android-studio-portable.git

    - name: Fetch upstream changes
      run: git fetch upstream --tags

    - name: Merge main branch
      run: |
        git checkout main
        git merge --no-edit upstream/main || true  # 自动处理无冲突合并

    - name: Commit merged changes
      uses: github-actions-x/commit@v2.9
      with:
        push-branch: 'main'
        force-add: 'true'
        default-commit-message: 'chore: sync upstream changes'

    - name: Push tags
      run: git push --tags origin
